FROM ubuntu:16.04

RUN apt-get update && \
    apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update && \
    apt-get install -y git python3.9 python3.9-venv

RUN ln -sf /usr/bin/python3.9 /usr/bin/python3
RUN mkdir /app
WORKDIR /app
RUN git clone https://github.com/watsoncm/damsafe.git .
COPY run.sh .
RUN chmod +x run.sh
ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV FLASK_APP=damsafe
ENV VIRTUAL_ENV=/app/env
RUN python3 -m venv $VIRTUAL_ENV
ENV PATH="$VIRTUAL_ENV/bin:$PATH"
RUN pip install -r requirements.txt

EXPOSE 5000

RUN flask init-db

CMD ./run.sh
